# Generated by Django 4.2 on 2025-03-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PL', 'Planning'), ('IP', 'In Progress'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='PL', max_length=2),
        ),
    ]
